export default {
  overview: "Aperçu",
  perforce: "Workflow Perforce",
  auth: "Authentification",
  characters: "Personnages",
  gas: "Gameplay Ability System",
  weapons: "Armes & projectiles",
  inventory: "Inventaire & hotbar",
  survival: "Système de survie",
  talents: "Arbre de talents",
  "ai-enemy": "IA ennemie & Behavior Tree",
  quests: "Donjon & missions",
  hud: "HUD & widgets",
  chat: "Chat & UI",
  persistence: "Persistance & systèmes de jeu",
  commandlets: "Commandlets éditeur",
  conventions: "Conventions",
};
